### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by CjjNoBug** [baozouai/rn-cartoon-app#10]
我在本地运行这个项目的时候为什么“首页”和“分类中图片不能显示出来啊，显示loading”

**Comment by baozouai** [comment]
> @CjjNoBug

图片在另外一个项目，由于图片9G，太大了，所以没有上传

**Comment by CjjNoBug** [comment]
喔喔，好的，请问你的图片是放在项目中哪个目录里的呢，我替换一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baozouai/rn-cartoon-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baozouai/rn-cartoon-app] 一些问题 (Issue #10)





  
@CjjNoBug
  
图片在另外一个项目，由于图片9G，太大了，所以没有上传
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by baozouai** [comment]
@CjjNoBug 

当时是看这个[教程](https://www.bilibili.com/video/BV1nE411N7js?spm_id_from=333.999.0.0)，你看下下面评论区，群里应该有对应的后端项目的，也有相应的图片资源

**Comment by CjjNoBug** [comment]
好的，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baozouai/rn-cartoon-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baozouai/rn-cartoon-app] 一些问题 (Issue #10)





 
@CjjNoBug
 
当时是看这个教程，你看下下面评论区，群里应该有对应的后端项目的，也有相应的图片资源
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CjjNoBug** [comment]
你好，我想问一下我现在这个项目的服务器已经和教程一样部署好了，但是现在运行app还是显示不出来数据，你知道怎么把服务器和app结合起来吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baozouai/rn-cartoon-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baozouai/rn-cartoon-app] 一些问题 (Issue #10)





 
@CjjNoBug
 
当时是看这个教程，你看下下面评论区，群里应该有对应的后端项目的，也有相应的图片资源
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
